{{- if .Values.persistence.pv.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
{{- if .Values.persistence.pv.pvname }}
  name: {{ .Values.persistence.pv.pvname }}
{{- else }}
  name: {{ template "name" . }}-pv
{{- end }}
  labels:
    app.kubernetes.io/name:  {{ template "name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  capacity:
    storage: {{ .Values.persistence.pv.capacity.storage }}
  accessModes:
    - {{ .Values.persistence.pv.accessMode | quote }}
  nfs:
    server: {{ .Values.persistence.pv.nfs.server }}
    path: {{ .Values.persistence.pv.nfs.path | quote }}
{{- end }}

